// Setup
const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');
const app = express();
const HTTP_PORT = process.env.PORT || 8080;
// Or use some other port number that you like better

// Add support for incoming JSON entities
app.use(bodyParser.json());

// Deliver the app's home page to browser clients
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '/index.html'));
});

// Array of strings
let people = [
  {
    id: 1,
    first_name: 'Sigismond',
    last_name: 'Freeland',
    email: 'sfreeland0@instagram.com',
    gender: 'Male',
    birthDate: '1998-11-07T17:57:53Z',
    web: 'https://nbcnews.com',
    creditScore: 230,
    rating: 11.78,
  },
  {
    id: 2,
    first_name: 'Wyatt',
    last_name: 'Swatton',
    email: 'wswatton1@guardian.co.uk',
    gender: 'Genderfluid',
    birthDate: '1995-07-05T01:35:50Z',
    web: 'https://state.tx.us',
    creditScore: 211,
    rating: 16.77,
  },
  {
    id: 3,
    first_name: 'Nikos',
    last_name: 'Deakin',
    email: 'ndeakin2@php.net',
    gender: 'Male',
    birthDate: '1994-07-28T04:47:18Z',
    web: 'http://51.la',
    creditScore: 474,
    rating: 8.67,
  },
  {
    id: 4,
    first_name: 'Bryn',
    last_name: 'Castree',
    email: 'bcastree3@hc360.com',
    gender: 'Male',
    birthDate: '1999-03-14T17:46:49Z',
    web: 'http://123-reg.co.uk',
    creditScore: 272,
    rating: 6.39,
  },
  {
    id: 5,
    first_name: 'Marika',
    last_name: 'Heavyside',
    email: 'mheavyside4@php.net',
    gender: 'Female',
    birthDate: '1999-06-02T08:04:18Z',
    web: 'https://imdb.com',
    creditScore: 608,
    rating: 8.57,
  },
  {
    id: 6,
    first_name: 'Darrick',
    last_name: 'Ilyas',
    email: 'dilyas5@clickbank.net',
    gender: 'Male',
    birthDate: '1994-02-06T12:33:42Z',
    web: 'http://youtube.com',
    creditScore: 358,
    rating: 4.69,
  },
  {
    id: 7,
    first_name: 'Berkeley',
    last_name: 'Burehill',
    email: 'bburehill6@surveymonkey.com',
    gender: 'Non-binary',
    birthDate: '1997-10-02T12:06:29Z',
    web: 'https://ftc.gov',
    creditScore: 476,
    rating: 6.54,
  },
  {
    id: 8,
    first_name: 'Thaxter',
    last_name: 'Haken',
    email: 'thaken7@seattletimes.com',
    gender: 'Male',
    birthDate: '1995-05-14T09:55:24Z',
    web: 'https://trellian.com',
    creditScore: 337,
    rating: 17.75,
  },
  {
    id: 9,
    first_name: 'Tabbatha',
    last_name: 'Balham',
    email: 'tbalham8@trellian.com',
    gender: 'Female',
    birthDate: '1995-08-16T13:01:55Z',
    web: 'http://blogspot.com',
    creditScore: 789,
    rating: 1.52,
  },
  {
    id: 10,
    first_name: 'Honor',
    last_name: 'Anfusso',
    email: 'hanfusso9@google.co.uk',
    gender: 'Female',
    birthDate: '1993-09-07T04:39:42Z',
    web: 'http://yelp.com',
    creditScore: 364,
    rating: 16.97,
  },
  {
    id: 11,
    first_name: 'Roseanne',
    last_name: 'Fotherby',
    email: 'rfotherbya@ehow.com',
    gender: 'Female',
    birthDate: '1998-03-21T13:59:32Z',
    web: 'https://seesaa.net',
    creditScore: 622,
    rating: 10.56,
  },
  {
    id: 12,
    first_name: 'Devlen',
    last_name: 'Tousey',
    email: 'dtouseyb@paypal.com',
    gender: 'Male',
    birthDate: '1994-07-08T07:10:10Z',
    web: 'https://1688.com',
    creditScore: 457,
    rating: 1.91,
  },
  {
    id: 13,
    first_name: 'Monti',
    last_name: 'Willeson',
    email: 'mwillesonc@hubpages.com',
    gender: 'Male',
    birthDate: '1996-08-28T08:14:34Z',
    web: 'http://dmoz.org',
    creditScore: 592,
    rating: 16.05,
  },
  {
    id: 14,
    first_name: 'Godfree',
    last_name: 'Lowensohn',
    email: 'glowensohnd@cbsnews.com',
    gender: 'Male',
    birthDate: '1999-02-01T03:28:13Z',
    web: 'https://domainmarket.com',
    creditScore: 644,
    rating: 14.32,
  },
  {
    id: 15,
    first_name: 'Sabine',
    last_name: 'Vitall',
    email: 'svitalle@msn.com',
    gender: 'Female',
    birthDate: '1998-11-17T02:48:44Z',
    web: 'https://shinystat.com',
    creditScore: 486,
    rating: 2.22,
  },
  {
    id: 16,
    first_name: 'Annice',
    last_name: 'Faussett',
    email: 'afaussettf@sitemeter.com',
    gender: 'Genderqueer',
    birthDate: '1993-12-02T16:29:00Z',
    web: 'https://unc.edu',
    creditScore: 644,
    rating: 12.39,
  },
  {
    id: 17,
    first_name: 'Archibold',
    last_name: 'Bonifazio',
    email: 'abonifaziog@gizmodo.com',
    gender: 'Male',
    birthDate: '1995-02-04T01:06:16Z',
    web: 'https://posterous.com',
    creditScore: 308,
    rating: 2.26,
  },
  {
    id: 18,
    first_name: 'Ash',
    last_name: 'Weedon',
    email: 'aweedonh@time.com',
    gender: 'Male',
    birthDate: '1999-11-11T10:06:47Z',
    web: 'http://jugem.jp',
    creditScore: 329,
    rating: 15.47,
  },
  {
    id: 19,
    first_name: 'Noam',
    last_name: 'Batson',
    email: 'nbatsoni@abc.net.au',
    gender: 'Non-binary',
    birthDate: '1995-04-21T21:17:27Z',
    web: 'http://msn.com',
    creditScore: 237,
    rating: 4.74,
  },
  {
    id: 20,
    first_name: 'Suzy',
    last_name: 'Dewer',
    email: 'sdewerj@deviantart.com',
    gender: 'Female',
    birthDate: '1998-06-12T02:12:15Z',
    web: 'http://uiuc.edu',
    creditScore: 546,
    rating: 14.2,
  },
  {
    id: 21,
    first_name: 'Maynord',
    last_name: 'Lemmers',
    email: 'mlemmersk@odnoklassniki.ru',
    gender: 'Male',
    birthDate: '1994-08-26T02:54:48Z',
    web: 'https://sphinn.com',
    creditScore: 642,
    rating: 12.42,
  },
  {
    id: 22,
    first_name: 'Bessy',
    last_name: 'Risbrough',
    email: 'brisbroughl@globo.com',
    gender: 'Female',
    birthDate: '1997-07-09T11:49:14Z',
    web: 'https://sbwire.com',
    creditScore: 545,
    rating: 19.75,
  },
  {
    id: 23,
    first_name: 'Diana',
    last_name: 'Bloomer',
    email: 'dbloomerm@tumblr.com',
    gender: 'Female',
    birthDate: '1995-07-23T10:42:23Z',
    web: 'http://360.cn',
    creditScore: 311,
    rating: 17.55,
  },
  {
    id: 24,
    first_name: 'Julio',
    last_name: 'Linfield',
    email: 'jlinfieldn@vistaprint.com',
    gender: 'Male',
    birthDate: '1996-06-12T22:03:26Z',
    web: 'http://yahoo.com',
    creditScore: 267,
    rating: 18.98,
  },
  {
    id: 25,
    first_name: 'Mariam',
    last_name: 'Diggins',
    email: 'mdigginso@lycos.com',
    gender: 'Female',
    birthDate: '1993-01-10T15:27:06Z',
    web: 'http://blog.com',
    creditScore: 478,
    rating: 4.37,
  },
  {
    id: 26,
    first_name: 'Zebulon',
    last_name: 'Pears',
    email: 'zpearsp@buzzfeed.com',
    gender: 'Genderfluid',
    birthDate: '1994-10-15T12:23:19Z',
    web: 'http://facebook.com',
    creditScore: 498,
    rating: 11.65,
  },
  {
    id: 27,
    first_name: 'Joye',
    last_name: 'Zaczek',
    email: 'jzaczekq@illinois.edu',
    gender: 'Agender',
    birthDate: '1994-06-04T17:35:23Z',
    web: 'https://i2i.jp',
    creditScore: 544,
    rating: 15.89,
  },
  {
    id: 28,
    first_name: 'Jaime',
    last_name: 'Losselyong',
    email: 'jlosselyongr@yahoo.com',
    gender: 'Female',
    birthDate: '1994-02-27T07:42:38Z',
    web: 'http://pagesperso-orange.fr',
    creditScore: 492,
    rating: 17.92,
  },
  {
    id: 29,
    first_name: 'Emilie',
    last_name: 'Chopping',
    email: 'echoppings@wikispaces.com',
    gender: 'Female',
    birthDate: '1993-02-13T06:23:35Z',
    web: 'https://va.gov',
    creditScore: 618,
    rating: 14.68,
  },
  {
    id: 30,
    first_name: 'Goldie',
    last_name: 'Helis',
    email: 'ghelist@abc.net.au',
    gender: 'Female',
    birthDate: '1996-09-28T18:08:15Z',
    web: 'https://oracle.com',
    creditScore: 469,
    rating: 5.77,
  },
  {
    id: 31,
    first_name: 'Ondrea',
    last_name: 'Hurren',
    email: 'ohurrenu@woothemes.com',
    gender: 'Female',
    birthDate: '1997-08-11T20:50:30Z',
    web: 'http://topsy.com',
    creditScore: 385,
    rating: 17.41,
  },
  {
    id: 32,
    first_name: 'Kerstin',
    last_name: 'Gepson',
    email: 'kgepsonv@opera.com',
    gender: 'Female',
    birthDate: '1998-08-31T22:24:48Z',
    web: 'http://foxnews.com',
    creditScore: 583,
    rating: 8.38,
  },
  {
    id: 33,
    first_name: 'Willis',
    last_name: 'Stribling',
    email: 'wstriblingw@comsenz.com',
    gender: 'Male',
    birthDate: '1993-06-29T04:11:45Z',
    web: 'http://yale.edu',
    creditScore: 478,
    rating: 19.38,
  },
  {
    id: 34,
    first_name: 'Colin',
    last_name: 'Gready',
    email: 'cgreadyx@virginia.edu',
    gender: 'Male',
    birthDate: '1999-10-11T11:15:14Z',
    web: 'http://springer.com',
    creditScore: 375,
    rating: 14.35,
  },
  {
    id: 35,
    first_name: 'Gui',
    last_name: 'Beacock',
    email: 'gbeacocky@loc.gov',
    gender: 'Bigender',
    birthDate: '1998-06-04T01:08:45Z',
    web: 'https://wikipedia.org',
    creditScore: 453,
    rating: 16.32,
  },
  {
    id: 36,
    first_name: 'Anatola',
    last_name: 'Vanderplas',
    email: 'avanderplasz@youku.com',
    gender: 'Female',
    birthDate: '1998-03-06T20:15:29Z',
    web: 'http://usa.gov',
    creditScore: 303,
    rating: 1.68,
  },
  {
    id: 37,
    first_name: 'Helli',
    last_name: 'Arrandale',
    email: 'harrandale10@free.fr',
    gender: 'Female',
    birthDate: '1997-07-26T08:53:20Z',
    web: 'http://artisteer.com',
    creditScore: 398,
    rating: 16.28,
  },
  {
    id: 38,
    first_name: 'Osmond',
    last_name: 'Tuckerman',
    email: 'otuckerman11@marketwatch.com',
    gender: 'Male',
    birthDate: '1995-11-30T07:00:05Z',
    web: 'https://storify.com',
    creditScore: 690,
    rating: 3.52,
  },
  {
    id: 39,
    first_name: 'Chelsey',
    last_name: 'Kidsley',
    email: 'ckidsley12@imgur.com',
    gender: 'Female',
    birthDate: '1992-09-24T12:15:07Z',
    web: 'http://deliciousdays.com',
    creditScore: 423,
    rating: 5.72,
  },
  {
    id: 40,
    first_name: 'Sargent',
    last_name: 'Curnock',
    email: 'scurnock13@youtube.com',
    gender: 'Genderqueer',
    birthDate: '1999-03-28T00:11:55Z',
    web: 'http://independent.co.uk',
    creditScore: 420,
    rating: 5.32,
  },
  {
    id: 41,
    first_name: 'Erick',
    last_name: 'Le Brum',
    email: 'elebrum14@redcross.org',
    gender: 'Male',
    birthDate: '1996-12-22T02:21:23Z',
    web: 'http://stumbleupon.com',
    creditScore: 470,
    rating: 19.53,
  },
  {
    id: 42,
    first_name: 'Lizabeth',
    last_name: 'Buey',
    email: 'lbuey15@harvard.edu',
    gender: 'Female',
    birthDate: '1998-12-17T11:37:49Z',
    web: 'http://theatlantic.com',
    creditScore: 439,
    rating: 1.88,
  },
  {
    id: 43,
    first_name: 'Robbie',
    last_name: 'Samudio',
    email: 'rsamudio16@chicagotribune.com',
    gender: 'Female',
    birthDate: '1995-01-19T05:09:20Z',
    web: 'http://jigsy.com',
    creditScore: 461,
    rating: 5.31,
  },
  {
    id: 44,
    first_name: 'Elsi',
    last_name: "O'Gavin",
    email: 'eogavin17@rambler.ru',
    gender: 'Female',
    birthDate: '1993-10-11T01:55:07Z',
    web: 'http://shop-pro.jp',
    creditScore: 337,
    rating: 5.69,
  },
  {
    id: 45,
    first_name: 'Atlante',
    last_name: 'Letterese',
    email: 'aletterese18@newyorker.com',
    gender: 'Female',
    birthDate: '1999-10-06T09:21:37Z',
    web: 'https://diigo.com',
    creditScore: 680,
    rating: 12.9,
  },
  {
    id: 46,
    first_name: 'Amaleta',
    last_name: 'Kealy',
    email: 'akealy19@yellowbook.com',
    gender: 'Polygender',
    birthDate: '1996-07-01T14:54:10Z',
    web: 'http://aol.com',
    creditScore: 727,
    rating: 13.59,
  },
  {
    id: 47,
    first_name: 'Bonnee',
    last_name: 'Jeffry',
    email: 'bjeffry1a@qq.com',
    gender: 'Female',
    birthDate: '1997-01-28T13:03:29Z',
    web: 'https://prweb.com',
    creditScore: 717,
    rating: 15.5,
  },
  {
    id: 48,
    first_name: 'Deck',
    last_name: 'Rapp',
    email: 'drapp1b@oaic.gov.au',
    gender: 'Male',
    birthDate: '1994-04-29T01:38:27Z',
    web: 'https://dyndns.org',
    creditScore: 578,
    rating: 17.68,
  },
  {
    id: 49,
    first_name: 'Kippy',
    last_name: 'Gudgen',
    email: 'kgudgen1c@amazonaws.com',
    gender: 'Female',
    birthDate: '1997-07-16T17:19:08Z',
    web: 'http://webeden.co.uk',
    creditScore: 240,
    rating: 13.65,
  },
  {
    id: 50,
    first_name: 'Ruby',
    last_name: 'Emlen',
    email: 'remlen1d@netvibes.com',
    gender: 'Male',
    birthDate: '1996-08-11T07:36:33Z',
    web: 'http://amazonaws.com',
    creditScore: 416,
    rating: 14.18,
  },
  {
    id: 51,
    first_name: 'Wait',
    last_name: 'Linley',
    email: 'wlinley1e@joomla.org',
    gender: 'Male',
    birthDate: '1999-01-10T20:29:17Z',
    web: 'https://deviantart.com',
    creditScore: 375,
    rating: 7.64,
  },
  {
    id: 52,
    first_name: 'Robinet',
    last_name: 'Davidsen',
    email: 'rdavidsen1f@harvard.edu',
    gender: 'Male',
    birthDate: '1999-10-16T09:32:05Z',
    web: 'http://netvibes.com',
    creditScore: 584,
    rating: 13.55,
  },
  {
    id: 53,
    first_name: 'Barnard',
    last_name: 'Staneland',
    email: 'bstaneland1g@slideshare.net',
    gender: 'Male',
    birthDate: '1997-01-28T19:36:08Z',
    web: 'https://shinystat.com',
    creditScore: 252,
    rating: 8.64,
  },
  {
    id: 54,
    first_name: 'Meggie',
    last_name: 'York',
    email: 'myork1h@instagram.com',
    gender: 'Polygender',
    birthDate: '1996-10-22T17:30:44Z',
    web: 'http://trellian.com',
    creditScore: 468,
    rating: 13.96,
  },
  {
    id: 55,
    first_name: 'Mandy',
    last_name: 'Stean',
    email: 'mstean1i@nbcnews.com',
    gender: 'Female',
    birthDate: '1999-10-11T04:56:19Z',
    web: 'https://timesonline.co.uk',
    creditScore: 242,
    rating: 1.87,
  },
  {
    id: 56,
    first_name: 'Kissee',
    last_name: 'Playhill',
    email: 'kplayhill1j@howstuffworks.com',
    gender: 'Female',
    birthDate: '1999-03-09T17:51:18Z',
    web: 'http://t.co',
    creditScore: 504,
    rating: 16.52,
  },
  {
    id: 57,
    first_name: 'Theressa',
    last_name: 'McMurdo',
    email: 'tmcmurdo1k@skyrock.com',
    gender: 'Female',
    birthDate: '1995-03-23T14:21:59Z',
    web: 'https://cdbaby.com',
    creditScore: 401,
    rating: 19.1,
  },
  {
    id: 58,
    first_name: 'Chiquia',
    last_name: 'Daice',
    email: 'cdaice1l@deviantart.com',
    gender: 'Female',
    birthDate: '1998-12-05T06:44:54Z',
    web: 'https://edublogs.org',
    creditScore: 578,
    rating: 14.02,
  },
  {
    id: 59,
    first_name: 'Kiersten',
    last_name: 'Bushrod',
    email: 'kbushrod1m@imageshack.us',
    gender: 'Female',
    birthDate: '1993-04-15T15:18:09Z',
    web: 'https://nih.gov',
    creditScore: 212,
    rating: 15.34,
  },
  {
    id: 60,
    first_name: 'Rory',
    last_name: 'Cluer',
    email: 'rcluer1n@ftc.gov',
    gender: 'Male',
    birthDate: '1993-02-01T01:02:57Z',
    web: 'http://wikimedia.org',
    creditScore: 272,
    rating: 11.97,
  },
  {
    id: 61,
    first_name: 'Diannne',
    last_name: 'Dwelley',
    email: 'ddwelley1o@seesaa.net',
    gender: 'Female',
    birthDate: '1995-03-15T08:20:22Z',
    web: 'https://soup.io',
    creditScore: 377,
    rating: 17.8,
  },
  {
    id: 62,
    first_name: 'Aguste',
    last_name: 'Dimitresco',
    email: 'adimitresco1p@homestead.com',
    gender: 'Agender',
    birthDate: '1998-02-27T15:07:33Z',
    web: 'https://statcounter.com',
    creditScore: 746,
    rating: 8.34,
  },
  {
    id: 63,
    first_name: 'Stephan',
    last_name: 'Chart',
    email: 'schart1q@google.ru',
    gender: 'Male',
    birthDate: '1995-10-16T23:30:46Z',
    web: 'https://microsoft.com',
    creditScore: 229,
    rating: 15.73,
  },
  {
    id: 64,
    first_name: 'Jobey',
    last_name: 'Matteini',
    email: 'jmatteini1r@gov.uk',
    gender: 'Female',
    birthDate: '1995-04-25T19:26:54Z',
    web: 'https://baidu.com',
    creditScore: 594,
    rating: 9.09,
  },
  {
    id: 65,
    first_name: 'Agnella',
    last_name: 'Winsome',
    email: 'awinsome1s@dedecms.com',
    gender: 'Female',
    birthDate: '1994-12-10T21:21:40Z',
    web: 'https://amazon.com',
    creditScore: 241,
    rating: 18.66,
  },
  {
    id: 66,
    first_name: 'Jilleen',
    last_name: 'Martinets',
    email: 'jmartinets1t@bing.com',
    gender: 'Female',
    birthDate: '1997-01-25T22:01:58Z',
    web: 'https://friendfeed.com',
    creditScore: 591,
    rating: 8.49,
  },
  {
    id: 67,
    first_name: 'Elena',
    last_name: 'Yurivtsev',
    email: 'eyurivtsev1u@discuz.net',
    gender: 'Female',
    birthDate: '1998-01-02T03:15:24Z',
    web: 'http://vk.com',
    creditScore: 492,
    rating: 17.78,
  },
  {
    id: 68,
    first_name: 'Kaye',
    last_name: 'Gabriel',
    email: 'kgabriel1v@blogspot.com',
    gender: 'Non-binary',
    birthDate: '1996-08-10T20:42:24Z',
    web: 'http://bloglines.com',
    creditScore: 736,
    rating: 19.86,
  },
  {
    id: 69,
    first_name: 'Maynard',
    last_name: 'Brach',
    email: 'mbrach1w@wufoo.com',
    gender: 'Genderqueer',
    birthDate: '1997-02-26T04:11:51Z',
    web: 'https://weebly.com',
    creditScore: 539,
    rating: 18.12,
  },
  {
    id: 70,
    first_name: 'Harris',
    last_name: 'Rookesby',
    email: 'hrookesby1x@slate.com',
    gender: 'Non-binary',
    birthDate: '1995-03-06T02:43:02Z',
    web: 'https://1688.com',
    creditScore: 237,
    rating: 19.75,
  },
  {
    id: 71,
    first_name: 'Poul',
    last_name: 'Neeson',
    email: 'pneeson1y@mtv.com',
    gender: 'Male',
    birthDate: '1993-09-17T15:47:32Z',
    web: 'http://cdbaby.com',
    creditScore: 642,
    rating: 15.61,
  },
  {
    id: 72,
    first_name: 'Tammara',
    last_name: 'Boulger',
    email: 'tboulger1z@live.com',
    gender: 'Polygender',
    birthDate: '1995-12-10T17:12:51Z',
    web: 'http://japanpost.jp',
    creditScore: 331,
    rating: 19.86,
  },
  {
    id: 73,
    first_name: 'Frasco',
    last_name: "O'Lenane",
    email: 'folenane20@discuz.net',
    gender: 'Male',
    birthDate: '1993-01-09T01:18:04Z',
    web: 'http://imageshack.us',
    creditScore: 566,
    rating: 15.07,
  },
  {
    id: 74,
    first_name: 'Layne',
    last_name: 'Van der Kruys',
    email: 'lvanderkruys21@scribd.com',
    gender: 'Female',
    birthDate: '1993-11-21T17:44:15Z',
    web: 'http://yolasite.com',
    creditScore: 644,
    rating: 6.05,
  },
  {
    id: 75,
    first_name: 'Milka',
    last_name: 'Isakov',
    email: 'misakov22@ted.com',
    gender: 'Genderfluid',
    birthDate: '1998-01-30T03:49:51Z',
    web: 'https://europa.eu',
    creditScore: 414,
    rating: 10.64,
  },
  {
    id: 76,
    first_name: 'Constancia',
    last_name: 'Carvilla',
    email: 'ccarvilla23@huffingtonpost.com',
    gender: 'Female',
    birthDate: '1993-05-23T05:40:11Z',
    web: 'https://amazon.com',
    creditScore: 361,
    rating: 1.24,
  },
  {
    id: 77,
    first_name: 'Townsend',
    last_name: 'Kienl',
    email: 'tkienl24@tuttocitta.it',
    gender: 'Male',
    birthDate: '1994-01-28T00:23:48Z',
    web: 'http://usda.gov',
    creditScore: 692,
    rating: 17.85,
  },
  {
    id: 78,
    first_name: 'Leola',
    last_name: 'Holley',
    email: 'lholley25@apache.org',
    gender: 'Female',
    birthDate: '1996-08-17T09:58:24Z',
    web: 'https://hibu.com',
    creditScore: 233,
    rating: 2.25,
  },
  {
    id: 79,
    first_name: 'Cherise',
    last_name: 'Vallantine',
    email: 'cvallantine26@dot.gov',
    gender: 'Female',
    birthDate: '1996-05-27T10:44:42Z',
    web: 'http://multiply.com',
    creditScore: 210,
    rating: 15.74,
  },
  {
    id: 80,
    first_name: 'Reeva',
    last_name: 'Clemenzi',
    email: 'rclemenzi27@g.co',
    gender: 'Female',
    birthDate: '1998-03-12T14:16:55Z',
    web: 'http://virginia.edu',
    creditScore: 510,
    rating: 3.7,
  },
  {
    id: 81,
    first_name: 'Corie',
    last_name: 'Ditt',
    email: 'cditt28@nasa.gov',
    gender: 'Female',
    birthDate: '1995-06-01T19:17:48Z',
    web: 'http://wp.com',
    creditScore: 733,
    rating: 7.83,
  },
  {
    id: 82,
    first_name: 'Aleece',
    last_name: 'Naper',
    email: 'anaper29@ycombinator.com',
    gender: 'Female',
    birthDate: '1999-08-08T20:25:25Z',
    web: 'http://fema.gov',
    creditScore: 294,
    rating: 14.55,
  },
  {
    id: 83,
    first_name: 'Brook',
    last_name: 'Blanning',
    email: 'bblanning2a@lycos.com',
    gender: 'Agender',
    birthDate: '1993-10-16T16:34:43Z',
    web: 'https://dailymail.co.uk',
    creditScore: 715,
    rating: 10.46,
  },
  {
    id: 84,
    first_name: 'Kriste',
    last_name: 'Gapper',
    email: 'kgapper2b@bizjournals.com',
    gender: 'Female',
    birthDate: '1994-07-10T10:18:47Z',
    web: 'http://canalblog.com',
    creditScore: 326,
    rating: 19.52,
  },
  {
    id: 85,
    first_name: 'Betty',
    last_name: 'Kasting',
    email: 'bkasting2c@mit.edu',
    gender: 'Female',
    birthDate: '1998-07-01T06:45:36Z',
    web: 'http://nasa.gov',
    creditScore: 696,
    rating: 1.28,
  },
  {
    id: 86,
    first_name: 'Sergio',
    last_name: 'Casino',
    email: 'scasino2d@theatlantic.com',
    gender: 'Male',
    birthDate: '1999-03-20T15:02:25Z',
    web: 'http://si.edu',
    creditScore: 441,
    rating: 17.31,
  },
  {
    id: 87,
    first_name: 'Adham',
    last_name: 'Clemerson',
    email: 'aclemerson2e@cisco.com',
    gender: 'Male',
    birthDate: '1997-11-22T01:48:09Z',
    web: 'https://umn.edu',
    creditScore: 727,
    rating: 2.6,
  },
  {
    id: 88,
    first_name: 'Emmaline',
    last_name: 'MacArdle',
    email: 'emacardle2f@hubpages.com',
    gender: 'Female',
    birthDate: '1997-11-15T02:40:20Z',
    web: 'https://ow.ly',
    creditScore: 494,
    rating: 13.96,
  },
  {
    id: 89,
    first_name: 'Maury',
    last_name: 'Feitosa',
    email: 'mfeitosa2g@cdbaby.com',
    gender: 'Male',
    birthDate: '1995-08-20T00:27:37Z',
    web: 'http://blogs.com',
    creditScore: 408,
    rating: 16.96,
  },
  {
    id: 90,
    first_name: 'Noreen',
    last_name: 'Christofle',
    email: 'nchristofle2h@biblegateway.com',
    gender: 'Female',
    birthDate: '1997-09-18T08:14:06Z',
    web: 'http://1688.com',
    creditScore: 213,
    rating: 5.04,
  },
  {
    id: 91,
    first_name: 'Robert',
    last_name: 'Mintram',
    email: 'rmintram2i@sina.com.cn',
    gender: 'Genderqueer',
    birthDate: '1998-11-21T06:42:41Z',
    web: 'https://nationalgeographic.com',
    creditScore: 627,
    rating: 3.22,
  },
  {
    id: 92,
    first_name: 'Edan',
    last_name: 'Esterbrook',
    email: 'eesterbrook2j@de.vu',
    gender: 'Male',
    birthDate: '1996-12-13T04:42:45Z',
    web: 'https://people.com.cn',
    creditScore: 239,
    rating: 11.83,
  },
  {
    id: 93,
    first_name: 'Sheridan',
    last_name: 'Clutterham',
    email: 'sclutterham2k@hubpages.com',
    gender: 'Male',
    birthDate: '1993-03-15T05:35:05Z',
    web: 'https://sbwire.com',
    creditScore: 626,
    rating: 1.97,
  },
  {
    id: 94,
    first_name: 'Annalise',
    last_name: 'Bartolini',
    email: 'abartolini2l@techcrunch.com',
    gender: 'Female',
    birthDate: '1996-09-26T09:19:24Z',
    web: 'https://sfgate.com',
    creditScore: 373,
    rating: 10.81,
  },
  {
    id: 95,
    first_name: 'Peter',
    last_name: 'Adey',
    email: 'padey2m@1und1.de',
    gender: 'Male',
    birthDate: '1993-12-11T13:21:15Z',
    web: 'http://skyrock.com',
    creditScore: 346,
    rating: 16.82,
  },
  {
    id: 96,
    first_name: 'Verge',
    last_name: 'Bayns',
    email: 'vbayns2n@sohu.com',
    gender: 'Male',
    birthDate: '1998-12-28T14:43:05Z',
    web: 'https://csmonitor.com',
    creditScore: 415,
    rating: 11.57,
  },
  {
    id: 97,
    first_name: 'Jud',
    last_name: 'Parsonson',
    email: 'jparsonson2o@printfriendly.com',
    gender: 'Male',
    birthDate: '1993-07-08T13:50:14Z',
    web: 'https://flickr.com',
    creditScore: 459,
    rating: 5.46,
  },
  {
    id: 98,
    first_name: 'Nichol',
    last_name: 'Trayhorn',
    email: 'ntrayhorn2p@g.co',
    gender: 'Female',
    birthDate: '1994-06-15T02:20:07Z',
    web: 'https://independent.co.uk',
    creditScore: 713,
    rating: 19.89,
  },
  {
    id: 99,
    first_name: 'Nolly',
    last_name: 'Lambotin',
    email: 'nlambotin2q@amazon.de',
    gender: 'Male',
    birthDate: '1999-10-01T00:51:33Z',
    web: 'http://samsung.com',
    creditScore: 581,
    rating: 9.39,
  },
  {
    id: 100,
    first_name: 'Kailey',
    last_name: 'Potts',
    email: 'kpotts2r@google.ca',
    gender: 'Female',
    birthDate: '1997-11-04T03:32:34Z',
    web: 'http://yelp.com',
    creditScore: 296,
    rating: 5.33,
  },
  {
    id: 101,
    first_name: 'Janene',
    last_name: 'Sneezem',
    email: 'jsneezem2s@alibaba.com',
    gender: 'Female',
    birthDate: '1997-03-05T23:24:35Z',
    web: 'https://statcounter.com',
    creditScore: 486,
    rating: 7.46,
  },
  {
    id: 102,
    first_name: 'Cthrine',
    last_name: 'Raper',
    email: 'craper2t@amazon.com',
    gender: 'Female',
    birthDate: '1995-01-24T08:58:20Z',
    web: 'http://vistaprint.com',
    creditScore: 520,
    rating: 9.51,
  },
  {
    id: 103,
    first_name: 'John',
    last_name: 'Brougham',
    email: 'jbrougham2u@sohu.com',
    gender: 'Male',
    birthDate: '1994-09-15T19:01:08Z',
    web: 'https://ow.ly',
    creditScore: 594,
    rating: 3.09,
  },
  {
    id: 104,
    first_name: 'Hughie',
    last_name: 'Jantel',
    email: 'hjantel2v@pen.io',
    gender: 'Non-binary',
    birthDate: '1997-01-17T20:26:16Z',
    web: 'http://google.com',
    creditScore: 600,
    rating: 1.83,
  },
  {
    id: 105,
    first_name: 'Aurora',
    last_name: 'Rucklesse',
    email: 'arucklesse2w@bluehost.com',
    gender: 'Female',
    birthDate: '1993-12-22T06:24:22Z',
    web: 'http://odnoklassniki.ru',
    creditScore: 773,
    rating: 2.74,
  },
  {
    id: 106,
    first_name: 'Fiorenze',
    last_name: 'Roostan',
    email: 'froostan2x@sphinn.com',
    gender: 'Female',
    birthDate: '1995-06-04T05:03:11Z',
    web: 'https://shop-pro.jp',
    creditScore: 535,
    rating: 9.58,
  },
  {
    id: 107,
    first_name: 'Pietro',
    last_name: 'Andino',
    email: 'pandino2y@europa.eu',
    gender: 'Male',
    birthDate: '1994-12-26T19:41:27Z',
    web: 'https://guardian.co.uk',
    creditScore: 698,
    rating: 13.44,
  },
  {
    id: 108,
    first_name: 'Halli',
    last_name: 'Rising',
    email: 'hrising2z@vistaprint.com',
    gender: 'Female',
    birthDate: '1994-07-13T11:32:16Z',
    web: 'https://tamu.edu',
    creditScore: 550,
    rating: 12.37,
  },
  {
    id: 109,
    first_name: 'Bevan',
    last_name: 'Bierman',
    email: 'bbierman30@sun.com',
    gender: 'Male',
    birthDate: '1996-05-26T07:01:21Z',
    web: 'https://google.it',
    creditScore: 657,
    rating: 3.06,
  },
  {
    id: 110,
    first_name: 'Devlen',
    last_name: 'Grzelczak',
    email: 'dgrzelczak31@squarespace.com',
    gender: 'Male',
    birthDate: '1994-04-15T14:48:20Z',
    web: 'https://wikia.com',
    creditScore: 704,
    rating: 7.98,
  },
  {
    id: 111,
    first_name: 'Kenny',
    last_name: 'Pughsley',
    email: 'kpughsley32@ow.ly',
    gender: 'Male',
    birthDate: '1994-11-01T03:23:53Z',
    web: 'http://ibm.com',
    creditScore: 255,
    rating: 5.82,
  },
  {
    id: 112,
    first_name: 'Bentley',
    last_name: 'Kerry',
    email: 'bkerry33@forbes.com',
    gender: 'Male',
    birthDate: '1999-08-09T04:20:22Z',
    web: 'https://census.gov',
    creditScore: 377,
    rating: 14.26,
  },
  {
    id: 113,
    first_name: 'Sandro',
    last_name: 'Drynan',
    email: 'sdrynan34@upenn.edu',
    gender: 'Male',
    birthDate: '1996-10-04T17:46:38Z',
    web: 'https://typepad.com',
    creditScore: 449,
    rating: 5.4,
  },
  {
    id: 114,
    first_name: 'Sondra',
    last_name: 'Rollinson',
    email: 'srollinson35@themeforest.net',
    gender: 'Female',
    birthDate: '1994-07-07T08:07:34Z',
    web: 'http://youtu.be',
    creditScore: 380,
    rating: 9.34,
  },
  {
    id: 115,
    first_name: 'Carney',
    last_name: 'Garrelts',
    email: 'cgarrelts36@nyu.edu',
    gender: 'Male',
    birthDate: '1994-08-04T19:16:27Z',
    web: 'https://dyndns.org',
    creditScore: 307,
    rating: 2.13,
  },
  {
    id: 116,
    first_name: 'Nananne',
    last_name: 'Lawler',
    email: 'nlawler37@yale.edu',
    gender: 'Female',
    birthDate: '1995-01-08T20:31:17Z',
    web: 'http://who.int',
    creditScore: 722,
    rating: 5.75,
  },
  {
    id: 117,
    first_name: 'Wernher',
    last_name: 'Sherer',
    email: 'wsherer38@woothemes.com',
    gender: 'Male',
    birthDate: '1999-09-09T12:44:01Z',
    web: 'http://vkontakte.ru',
    creditScore: 739,
    rating: 14.53,
  },
  {
    id: 118,
    first_name: 'Irvin',
    last_name: 'Metham',
    email: 'imetham39@macromedia.com',
    gender: 'Male',
    birthDate: '1996-01-26T15:12:37Z',
    web: 'http://privacy.gov.au',
    creditScore: 743,
    rating: 11.66,
  },
  {
    id: 119,
    first_name: 'Cymbre',
    last_name: 'Nerheny',
    email: 'cnerheny3a@auda.org.au',
    gender: 'Bigender',
    birthDate: '1994-12-19T22:58:49Z',
    web: 'http://sohu.com',
    creditScore: 414,
    rating: 12.74,
  },
  {
    id: 120,
    first_name: 'Amitie',
    last_name: 'Hitzmann',
    email: 'ahitzmann3b@addtoany.com',
    gender: 'Female',
    birthDate: '1993-12-21T14:12:06Z',
    web: 'https://last.fm',
    creditScore: 492,
    rating: 20.0,
  },
  {
    id: 121,
    first_name: 'Dacia',
    last_name: 'Cattlow',
    email: 'dcattlow3c@joomla.org',
    gender: 'Female',
    birthDate: '1997-03-16T16:58:37Z',
    web: 'http://upenn.edu',
    creditScore: 665,
    rating: 8.86,
  },
  {
    id: 122,
    first_name: 'Thedric',
    last_name: 'Reinbach',
    email: 'treinbach3d@wikipedia.org',
    gender: 'Male',
    birthDate: '1994-12-25T07:07:30Z',
    web: 'https://nymag.com',
    creditScore: 537,
    rating: 2.67,
  },
  {
    id: 123,
    first_name: 'Norrie',
    last_name: 'Berzen',
    email: 'nberzen3e@usatoday.com',
    gender: 'Bigender',
    birthDate: '1998-12-31T19:41:58Z',
    web: 'https://simplemachines.org',
    creditScore: 708,
    rating: 8.86,
  },
  {
    id: 124,
    first_name: 'Lyon',
    last_name: 'Duffet',
    email: 'lduffet3f@mlb.com',
    gender: 'Male',
    birthDate: '1998-06-26T22:11:02Z',
    web: 'https://slideshare.net',
    creditScore: 349,
    rating: 5.24,
  },
  {
    id: 125,
    first_name: 'Ingmar',
    last_name: 'Collihole',
    email: 'icollihole3g@pinterest.com',
    gender: 'Male',
    birthDate: '1995-12-01T03:30:29Z',
    web: 'https://ehow.com',
    creditScore: 367,
    rating: 19.45,
  },
  {
    id: 126,
    first_name: 'Johann',
    last_name: 'Belchem',
    email: 'jbelchem3h@go.com',
    gender: 'Male',
    birthDate: '1993-11-11T03:46:09Z',
    web: 'http://aol.com',
    creditScore: 711,
    rating: 9.45,
  },
  {
    id: 127,
    first_name: 'Zeb',
    last_name: 'Pipes',
    email: 'zpipes3i@cnet.com',
    gender: 'Male',
    birthDate: '1998-12-05T14:03:04Z',
    web: 'http://sogou.com',
    creditScore: 228,
    rating: 11.99,
  },
  {
    id: 128,
    first_name: 'Vasilis',
    last_name: 'Loughman',
    email: 'vloughman3j@vimeo.com',
    gender: 'Bigender',
    birthDate: '1992-12-13T19:39:57Z',
    web: 'http://pagesperso-orange.fr',
    creditScore: 546,
    rating: 16.67,
  },
  {
    id: 129,
    first_name: 'Brenna',
    last_name: 'Beinke',
    email: 'bbeinke3k@wikia.com',
    gender: 'Female',
    birthDate: '1994-12-12T04:23:00Z',
    web: 'http://flickr.com',
    creditScore: 250,
    rating: 10.11,
  },
  {
    id: 130,
    first_name: 'Linea',
    last_name: 'Flahive',
    email: 'lflahive3l@prnewswire.com',
    gender: 'Female',
    birthDate: '1995-05-21T22:43:25Z',
    web: 'https://newsvine.com',
    creditScore: 382,
    rating: 14.41,
  },
  {
    id: 131,
    first_name: 'Monika',
    last_name: 'Haywood',
    email: 'mhaywood3m@t.co',
    gender: 'Female',
    birthDate: '1995-11-08T07:28:19Z',
    web: 'https://jimdo.com',
    creditScore: 524,
    rating: 14.2,
  },
  {
    id: 132,
    first_name: 'Harriot',
    last_name: 'Baudou',
    email: 'hbaudou3n@cargocollective.com',
    gender: 'Female',
    birthDate: '1994-05-25T12:19:25Z',
    web: 'http://unicef.org',
    creditScore: 335,
    rating: 16.64,
  },
  {
    id: 133,
    first_name: 'Caroline',
    last_name: 'Janse',
    email: 'cjanse3o@list-manage.com',
    gender: 'Female',
    birthDate: '1997-06-12T16:26:13Z',
    web: 'https://creativecommons.org',
    creditScore: 640,
    rating: 13.83,
  },
  {
    id: 134,
    first_name: 'Hana',
    last_name: 'McCullouch',
    email: 'hmccullouch3p@stanford.edu',
    gender: 'Female',
    birthDate: '1995-12-08T05:35:51Z',
    web: 'https://amazonaws.com',
    creditScore: 743,
    rating: 13.08,
  },
  {
    id: 135,
    first_name: 'De',
    last_name: 'Brehat',
    email: 'dbrehat3q@vistaprint.com',
    gender: 'Female',
    birthDate: '1995-12-12T08:09:25Z',
    web: 'https://dropbox.com',
    creditScore: 208,
    rating: 7.35,
  },
  {
    id: 136,
    first_name: 'Eirena',
    last_name: 'Manford',
    email: 'emanford3r@cdbaby.com',
    gender: 'Genderfluid',
    birthDate: '1996-04-04T09:39:47Z',
    web: 'http://psu.edu',
    creditScore: 318,
    rating: 6.23,
  },
  {
    id: 137,
    first_name: 'Inigo',
    last_name: 'Saul',
    email: 'isaul3s@livejournal.com',
    gender: 'Male',
    birthDate: '1992-09-16T05:45:26Z',
    web: 'https://ovh.net',
    creditScore: 753,
    rating: 17.88,
  },
  {
    id: 138,
    first_name: 'Amalita',
    last_name: 'Nevins',
    email: 'anevins3t@1und1.de',
    gender: 'Female',
    birthDate: '1999-03-31T12:03:59Z',
    web: 'http://amazon.com',
    creditScore: 326,
    rating: 11.73,
  },
  {
    id: 139,
    first_name: 'Elsy',
    last_name: 'Henze',
    email: 'ehenze3u@typepad.com',
    gender: 'Female',
    birthDate: '1995-12-04T17:39:33Z',
    web: 'https://qq.com',
    creditScore: 430,
    rating: 7.47,
  },
  {
    id: 140,
    first_name: 'Maximilian',
    last_name: 'Noddings',
    email: 'mnoddings3v@netlog.com',
    gender: 'Male',
    birthDate: '1998-10-03T12:01:03Z',
    web: 'http://sphinn.com',
    creditScore: 340,
    rating: 4.32,
  },
  {
    id: 141,
    first_name: 'Leena',
    last_name: 'Brambill',
    email: 'lbrambill3w@com.com',
    gender: 'Female',
    birthDate: '1994-08-18T02:36:35Z',
    web: 'https://mtv.com',
    creditScore: 735,
    rating: 15.96,
  },
  {
    id: 142,
    first_name: 'Griz',
    last_name: 'Cawsy',
    email: 'gcawsy3x@tiny.cc',
    gender: 'Male',
    birthDate: '1996-03-11T14:14:55Z',
    web: 'https://about.me',
    creditScore: 292,
    rating: 8.96,
  },
  {
    id: 143,
    first_name: 'Gerrie',
    last_name: 'Ower',
    email: 'gower3y@utexas.edu',
    gender: 'Female',
    birthDate: '1998-02-16T17:59:34Z',
    web: 'http://wikimedia.org',
    creditScore: 757,
    rating: 1.34,
  },
  {
    id: 144,
    first_name: 'Emilio',
    last_name: 'Buttler',
    email: 'ebuttler3z@blogspot.com',
    gender: 'Male',
    birthDate: '1994-10-06T18:18:06Z',
    web: 'https://bigcartel.com',
    creditScore: 642,
    rating: 19.34,
  },
  {
    id: 145,
    first_name: 'Anet',
    last_name: 'Estrella',
    email: 'aestrella40@spotify.com',
    gender: 'Female',
    birthDate: '1994-09-01T05:08:01Z',
    web: 'http://slashdot.org',
    creditScore: 766,
    rating: 8.05,
  },
  {
    id: 146,
    first_name: 'Lionel',
    last_name: "D'Aubney",
    email: 'ldaubney41@nationalgeographic.com',
    gender: 'Male',
    birthDate: '1999-02-01T16:58:46Z',
    web: 'http://ow.ly',
    creditScore: 525,
    rating: 5.79,
  },
  {
    id: 147,
    first_name: 'Bonita',
    last_name: 'Brandsma',
    email: 'bbrandsma42@theglobeandmail.com',
    gender: 'Female',
    birthDate: '1998-10-20T20:27:44Z',
    web: 'http://mysql.com',
    creditScore: 369,
    rating: 15.71,
  },
  {
    id: 148,
    first_name: 'Henri',
    last_name: 'McLinden',
    email: 'hmclinden43@ucsd.edu',
    gender: 'Male',
    birthDate: '1998-12-27T13:42:57Z',
    web: 'https://histats.com',
    creditScore: 362,
    rating: 14.39,
  },
  {
    id: 149,
    first_name: 'Lyda',
    last_name: 'Andrez',
    email: 'landrez44@spiegel.de',
    gender: 'Female',
    birthDate: '1998-05-26T16:45:25Z',
    web: 'http://networkadvertising.org',
    creditScore: 417,
    rating: 19.56,
  },
  {
    id: 150,
    first_name: 'Bryan',
    last_name: 'Nuccii',
    email: 'bnuccii45@npr.org',
    gender: 'Genderfluid',
    birthDate: '1996-09-24T02:12:09Z',
    web: 'https://webmd.com',
    creditScore: 418,
    rating: 8.15,
  },
];

// Get all - Sorting data by lastName, firstName, and creditScore
let c = people.map((p) => p);

c.sort(function (a, b) {
  return (
    a.last_name.localeCompare(b.last_name) ||
    a.first_name.localeCompare(b.first_name) ||
    0
  );
});

// Get all
app.get('/api/items', (req, res) => {
  res.json(people);
});

// Get one
app.get('/api/items/:itemId', (req, res) => {
  const itemId = req.params.itemId;
  if (itemId >= 0 && itemId < people.length) {
    res.json({ person: people[itemId - 1] });
  } else {
    res.status(404).send('Resource not found');
  }
});

// Add new
// This route expects a JSON object in the body, e.g. { "firstName": "Peter", "lastName": "McIntyre" }
app.post('/api/items', (req, res) => {
  // Extract the incoming data from { "colourName": "Purple" }

  let newPerson = {
    id: req.body.id,
    first_name: req.body.firstName,
    last_name: req.body.lastName,
    gender: req.body.gender,
    birthDate: req.body.birthDate,
    email: req.body.email,
    web: req.body.web,
    creditScore: req.body.creditScore,
    rating: req.body.rating,
  };

  console.log(newPerson);

  // Add another item to the array
  people.push(newPerson);
  // Return the result; RFC 7231 tells us that it must return HTTP status 201
  res.status(201).json({
    message: `added ${newPerson.id}, ${newPerson.first_name}, ${newPerson.last_name}, ${newPerson.gender}, ${newPerson.birthDate}, ${newPerson.email}, ${newPerson.web}, ${newPerson.creditScore}, ${newPerson.rating} as item identifier ${people.length}`,
  });
});

// Edit existing
// This route expects a JSON object in the body, e.g. { "id": 123, "firstName": "Peter", "lastName": "McIntyre" }
app.put('/api/items/:id', (req, res) => {
  const itemId = req.params.id;
  if (itemId >= 0 && itemId < people.length) {
    let updatedPerson = {
      id: req.body.id,
      first_name: req.body.firstName,
      last_name: req.body.lastName,
      gender: req.body.gender,
      birthDate: req.body.birthDate,
      email: req.body.email,
      web: req.body.web,
      creditScore: req.body.creditScore,
      rating: req.body.rating,
    };
    people[itemId - 1] = updatedPerson;
    res.json({
      message: `Updated person with identifier: ${itemId} to ${updatedPerson.id}, ${updatedPerson.first_name}, ${updatedPerson.last_name}, ${updatedPerson.gender}, ${updatedPerson.birthDate}, ${updatedPerson.email}, ${updatedPerson.web}, ${updatedPerson.creditScore}, ${updatedPerson.rating}`,
    });
  } else {
    res.status(404).send('Resource not found');
  }
});

// Delete item
app.delete('/api/items/:id', (req, res) => {
  const itemId = req.params.id;
  if (itemId >= 0 && itemId < people.length) {
    const deletedItem = people.splice(itemId - 1, 1)[0];
    res
      .status(200)
      .json({ message: `deleted user with identifier: ${deletedItem.id}` });
  } else {
    res.status(404).send('Resource not found');
  }
});

// Resource not found (this should be at the end)
app.use((req, res) => {
  res.status(404).send('Resource not found');
});

// Tell the app to start listening for requests
app.listen(HTTP_PORT, () => {
  console.log('Ready to handle requests on port ' + HTTP_PORT);
});
